name: com.asdvek.MinecraftASKimble.MinecraftASKimblePlugin
version: 1.0
main: com.asdvek.MinecraftASKimble.MinecraftASKimblePlugin
api-version: 1.15

commands:
  kimble:
    description: Manage a kimble game instance.
    usage: /<command>